name: Build and Deploy Notes

on:
  push:
    branches:
      - master

jobs:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build Notes
      run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Hosting Service (e.g., Netlify)
      run: |
        # Add your deployment command or script here.
        # For example, deploying to Netlify:
        npx netlify-cli deploy --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
